---
title: "Hooded sprayer studies in Missouri, Nebraska and Wisconsin"
author: "Maxwel Coura Oliveira, Guilherme Alves and Rodrigo Werle"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty: 
    theme: architect
    highlight: github
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.align = 'center')
```

# Deposition downwind ------------------------------------------------------



## Filter data

```{r}
data_dw <- data %>% 
  filter(type == "downwind") %>% 
  mutate(pass = factor(pass)) %>% 
  group_by(location, pass, block) 
```



## Visualize

```{r}
data_dw %>% 
  ggplot(aes(x = distance_m, y = deposition, color = nozzle)) +
  geom_point() +
  facet_grid(~ location)
# some trt have rapid decrease and some trt have linear trend
```


## Visualize (log scale)


```{r}
data_dw %>% 
  filter(location == "wisconsin") %>% 
#  unite("trt", c("solution", "sprayer", "nozzle")) %>% 
  ggplot(aes(x = log(distance_m), y = log(deposition), color = nozzle)) +
  geom_point() +
  facet_grid(sprayer ~ solution) +
  geom_smooth(method = "lm") 
# better go with log scale
```

## Normal distribution

```{r}
data_dw %>% 
  ggplot(aes(x = log(deposition))) +
  geom_histogram() +
  facet_grid(~location)
```

# Linear Model

## Arrange dataset

```{r}
data_dw1 <- data_dw %>% 
  group_by(location, solution, sprayer, nozzle) %>% 
  nest()

data_dw1
```

### Model function

```{r}
model <- function(df){
  lmer(log(deposition) ~ log(distance_m) + 
         (1|block), REML = FALSE, data = df)
}
```

### Fit model and confidence intervals

```{r warning=FALSE, message = FALSE}
data_dw2 <- data_dw1 %>% 
  mutate(model = map(data, model),
         summary = map(model, broom.mixed::tidy),
         confint = map(model, confint))
```

```{r}
wi <- data_dw2 %>% 
  filter(location == "wisconsin")
```





```{r}
# Predict 110 and 220
new_points <- expand.grid(`log(distance_m)` = c(3.512381, 4.205528))
new_points
```


```{r warning = FALSE}
#Getting predited values
dat <- data.frame(distance_m = seq(0, 100, 2))
mean_pred <- predict(wi$model[[3]], ype_pred = c( "link")) 

mean_pred
```


```{r}
#Getting conf intervals
conf_int_pred <- predict(lm_fit, 
                         new_data = new_points, 
                         type = "conf_int")
conf_int_pred
```



### Get parameters from models

```{r}
params <- data_dw2 %>% 
  unnest(summary) %>% 
  filter(effect == "fixed") %>% 
  mutate(estimate_exp = exp(estimate),
         estimate_exp = case_when(
           term == "log(distance_m)" ~ -estimate_exp,
           TRUE                      ~ estimate_exp
         )) %>% 
  dplyr::select(location, solution, sprayer, nozzle, term, estimate, std.error, statistic, p.value, estimate_exp) %>% 
  mutate(p.value = round(p.value, 3)) %>% 
  mutate(term = fct_recode(term,
                           slope = "log(distance_m)"),
         term = fct_recode(term,
                           Intercept = "(Intercept)")) %>% 
  unite("trt", c("solution", "sprayer", "nozzle"), sep = " ", remove = FALSE)

params
```




### Get confidence intervals

```{r}
get_cis <- function(number){
  exp(data_dw2$confint[[number]]) %>%
    as_tibble() %>%
    slice_tail(n=2)
} 

number <- as_tibble(c(1:30))

intervals <- number %>%
  mutate(interval = map(value, get_cis)) %>%
  unnest(interval)

# join to main dataset
downwind_final <- params %>%
  bind_cols(intervals) %>%
  rename(lower = `2.5 %`,
         upper = `97.5 %`) %>%
  mutate(lower = case_when(
           term == "log(distance_m)" ~ -lower,
         TRUE                        ~ lower
         ),
         upper = case_when(
           term == "log(distance_m)" ~ -upper,
         TRUE                        ~ upper,
         )) %>% 
  mutate(across(where(is_double), round, 3))
```


## Distance of deposition at 0

```{r}
distance_final <- downwind_final %>% 
  dplyr::select(trt, term, estimate_exp) %>% 
  pivot_wider(
              names_from = term, 
              values_from = estimate_exp) 
```


```{r}
distance_function <- function(int, slope, y = 0) {
  distance = (y - int) / slope
  return(distance)
}

distance_final1 <- distance_final %>% 
  mutate(distance_m = map2_dbl(Intercept, slope, distance_function),
         distance_m = round(distance_m, 10)) 
```





## Predict

```{r}
downwind_final1 <- downwind_final %>% 
  pivot_wider(id_cols = location:nozzle,
              names_from = term, 
              values_from = estimate_exp) 
```


```{r}
linear <- function(a, b, d) {
  y = a + b*d
  return(y)
}

linear(distance_final1$Intercept, distance_final1$slope, distance_final1$distance_m)
```















```{r}
a <- downwind_final %>% 
  filter(term == "Intercept") %>% 
  filter(location == "wisconsin") %>%
    mutate(trt = factor(trt, levels = c(
    "Intact Hood TTI", "Intact Hood ULD", "Water Hood TTI",
    "Intact Hood AIXR", "Water Hood AIXR", "Water Hood ULD",
    "Intact Open TTI", "Water Open TTI", "Intact Open ULD",
    "Water Open ULD", "Water Open AIXR", "Intact Open AIXR"
  ))) %>% 
  ggplot(aes(x = reorder(trt, estimate_exp), y = estimate_exp, color = trt)) +
  geom_point(size = 2, stroke = 1) +
  scale_color_brewer(palette = "Paired") +
  geom_linerange(aes(ymin = lower, ymax = upper), size = 1.5) +
  coord_flip() +
  geom_text(aes(x = 1.5, y = 25,
                label = "Lower values lower spray \nparticle deposition"),
            stat = "unique", family = "bell",
            size = 4, color = "darkcyan") +
  labs(title = "Intercept at downwind", 
       y = expression(paste("Spray particle deposition (\u03b7L/cm"^"2",")")), x = "") +
  theme_test() +
  theme(legend.position = "none",
        plot.title = element_markdown(family = "fredoka", color = "#282728")) 
a
```


```{r}
b <- downwind_final %>% 
  filter(term == "slope") %>% 
  filter(location == "wisconsin") %>% 
  mutate(trt = factor(trt, levels = c(
    "Intact Hood TTI", "Intact Hood ULD", "Water Hood TTI",
    "Intact Hood AIXR", "Water Hood AIXR", "Water Hood ULD",
    "Intact Open TTI", "Water Open TTI", "Intact Open ULD",
    "Water Open ULD", "Water Open AIXR", "Intact Open AIXR"
  ))) %>% 
  ggplot(aes(x = trt, y = estimate_exp, color = trt)) +
  geom_point(size = 2, stroke = 1) +
  scale_color_brewer(palette = "Paired") +
  geom_linerange(aes(ymin = -lower, ymax = -upper), size = 1.5) +
  coord_flip() +
  geom_text(aes(x = 11.6, y = -0.43,
                label = "Higher values lower spray \nparticle deposition rate"),
            stat = "unique", family = "bell",
            size = 4, color = "darkcyan") +
  labs(title = "Slope at downwind", 
       y = expression(paste("Spray particle deposition (\u03b7L/cm"^"2",")")), x = "") +
  theme_test() +
  theme(legend.position = "none",
        plot.title = element_markdown(family = "fredoka", color = "#282728")) 
b
```


```{r}
c <- distance_final1 %>% 
  filter(location == "wisconsin") %>% 
    mutate(trt = factor(trt, levels = c(
    "Intact Hood TTI", "Intact Hood ULD", "Water Hood TTI",
    "Intact Hood AIXR", "Water Hood AIXR", "Water Hood ULD",
    "Intact Open TTI", "Water Open TTI", "Intact Open ULD",
    "Water Open ULD", "Water Open AIXR", "Intact Open AIXR"
  ))) %>% 
  ggplot(aes(x = reorder(trt, distance_m), 
             y = distance_m,
             label = distance_m, fill = trt)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  geom_label(aes(label = round(distance_m, 0))) +
  scale_fill_brewer(palette = "Paired") +
  geom_text(aes(x = 1, y = 70),
                label = expression(paste("Distance where spray \nparticle deposition reached 0 nL/cm"^"2"," ")),
            stat = "unique", family = "bell",
            size = 4, color = "darkcyan") +
  labs(title = "Predicted downwind distance (m)", 
       y = "", x = "") +
#  geom_label(aes(label = distance_0)) +
  ylim(0,115) +
  theme_test() +
  theme(legend.position = "none",
        plot.title = element_markdown(family = "fredoka", color = "#282728"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
c
```

Distance at 110 ft (33.528m)

```{r}

```






# AUC


```{r}
id_df <- data_dw %>% 
  distinct(pass, block, location) %>% 
  ungroup() %>% 
  mutate(id = as_factor(dplyr::row_number()))
```

```{r}
id_df1 <- data_dw %>% 
  left_join(id_df) 
```


```{r}
auc_cal <- function(number){
  df <- id_df1 %>% 
    filter(id == number)  
  
  audps(df$deposition, df$distance_m, type="absolute") 
}

auc_data <- id_df1 %>% 
  group_by(id) %>% 
  nest() %>% 
  mutate(auc = map_dbl(id, auc_cal)) %>% 
  ungroup(id) %>% 
  unnest() 
```

```{r}
auc_data1 <- auc_data %>% 
  filter(distance_m == 1)
```



```{r}
auc_data1 %>% 
  ggplot(aes(x = log(auc))) + 
  geom_histogram() + 
  facet_grid(~ location)
```


```{r}
auc_data2 <- auc_data1 %>% 
  unite("trt", c("solution", "sprayer", "nozzle"), sep = " ", remove = FALSE) %>% 
  nest(-location) %>% 
  filter(location != "missouri")
```


```{r}
auc_model <- function(df) {
  lmer(log(auc) ~ solution * sprayer * nozzle + (1|block), data=df)
}
```


```{r}
auc_data3 <- auc_data2 %>% 
  mutate(model = map(data, auc_model),
         anova = map(model, anova))
```


```{r}
auc_data3 %>% 
  unnest(anova)
```
```{r}
auc_data3$anova[[2]]
```

```{r}
emm_wi <- emmeans(auc_data3$model[[2]], ~ solution * sprayer, cont="pairwise", 
                      adjust="none", alpha=0.05, type = "response")
emm_wi

emm_wi_noz <- emmeans(auc_data3$model[[2]], ~ nozzle, cont="pairwise", 
                      adjust="none", alpha=0.05, type = "response")
emm_wi_noz
```

```{r}
wis_cld <- as_tibble(multcomp::cld(emm_wi$emmeans, alpha=0.05, 
                         Letters=letters, adjust="none", reversed = TRUE)) %>% 
  unite("trt", c("solution", "sprayer"), sep = " ", remove = FALSE)

wis_cld_noz <- as_tibble(multcomp::cld(emm_wi_noz$emmeans, alpha=0.05, 
                         Letters=letters, adjust="none", reversed = TRUE)) %>% 
  dplyr::select(-SE, -df) %>% 
  rename(Nozzle = nozzle, 
         AUC = response, 
         Group = .group) %>% 
  mutate_if(is_double, ~round(.,1)) %>% 
  unite("CI", c("lower.CL", "upper.CL"), sep = "-") 


wis_cld_noz
```

```{r}
auc_wi <- wis_cld %>% 
ggplot(aes(x=reorder(trt, response), 
               y=response, color=trt, label = .group)) + 
  geom_point(size = 2, stroke = 1) +
  ylim(0,75) +
 scale_color_brewer(palette = "Paired") +
  theme_test() + 
  geom_text(aes(x = 3.5, y = 20,
                label = "Lower values \nless spray particle \ndeposition \nfrom 1 to 60 m"),
            stat = "unique", family = "bell",
            size = 4, color = "darkcyan") +
  labs(title = "Area under the curve at downwind",
       y= "", x="") +
  annotate(geom = "table", x = 1.7, y = 20, color = "#282728",
           label = list(wis_cld_noz), 
           vjust = 1, hjust = 0) +
  geom_linerange(aes(ymin = lower.CL, ymax = upper.CL), size=1.5) + 
  coord_flip() +
  theme(legend.position = "none",
        plot.title = element_markdown(family = "fredoka", color = "#282728")) 
  auc_wi 
```

```{r}
auc_wi_noz <- wis_cld_noz %>% 
ggplot(aes(x=reorder(nozzle, response), 
               y=response, color=nozzle, label = .group)) + 
  geom_point(size = 2, stroke = 1) +
#  ylim(0,100) +
 scale_color_brewer(palette = "Paired") +
  theme_test() + 
  geom_text(aes(x = 3.5, y = 5,
                label = "Nozzle"),
            stat = "unique", family = "bell",
            size = 4, color = "darkcyan") +
  labs(title = "",
       y= "", x="") +
  geom_linerange(aes(ymin = lower.CL, ymax = upper.CL), size=1.5) + 
  coord_flip() +
  theme(legend.position = "none",
        plot.title = element_markdown(family = "fredoka", color = "#282728"),
        plot.background = element_rect(fill = "#F5F5F5", color = NA))
auc_wi_noz
```

```{r emmeans_function, eval=FALSE, include=FALSE}
auc_data4 <- auc_data3 %>% 
  mutate(
    emmeans = pmap(
      .l = list(
        object = model, 
        specs = "solution * sprayer",
        type= "response",
#        cont="pairwise", 
        adjust="none"
      ),
      .f = emmeans
    )
  ) 



# full data frame with all means and CIs 
auc_data4 %>% 
  mutate(emm2 = map(emmeans, data.frame)) %>% 
  unnest(emm2)
#You can filter and make a data frame for each population and dat

cld_function <- function(emmeans) {
  if(requireNamespace("multcomp")) {
    multcomp::cld(emmeans, alpha=0.05, Letters=letters, adjust="none", reversed = TRUE)
}
}

auc_data5 <- auc_data4 %>% 
  mutate(cld = map(emmeans, cld_function))

# here is similar to emmeans but you have letters
auc_data6 <- auc_data5 %>% 
  unnest(cld) %>% 
  mutate(label_at = upper.CL - response + 15)
# You can also filter and make specific data frames

auc_wi <- auc_data6 %>% 
  filter(location == "wisconsin") %>% 
    mutate(trt = factor(trt, levels = c(
    "Intact Hood TTI", "Intact Hood ULD", "Water Hood TTI",
    "Intact Hood AIXR", "Water Hood AIXR", "Water Hood ULD",
    "Intact Open TTI", "Water Open TTI", "Intact Open ULD",
    "Water Open ULD", "Water Open AIXR", "Intact Open AIXR"
  ))) %>%
ggplot(aes(x=reorder(trt, response), 
               y=response, color=trt, label = .group)) + 
  geom_point(size = 2, stroke = 1) +
#  ylim(0,100) +
 scale_color_brewer(palette = "Paired") +
  geom_text(nudge_y = c(66.0, 60.2, 53.6, 36.8, 34.4, 28.3,  
                        19.1, 17.5, 11.6, 7.1, 3.8, 3.1)) +
  theme_test() + 
  geom_text(aes(x = 1.5, y = 100,
                label = "Lower values less spray \nparticle deposition from 1 to 60 m"),
            stat = "unique", family = "bell",
            size = 4, color = "darkcyan") +
  labs(title = "Area under the curve at downwind",
       y= "", x="") +
  geom_linerange(aes(ymin = lower.CL, ymax = upper.CL), size=1.5) + 
  coord_flip() +
  theme(legend.position = "none",
        plot.title = element_markdown(family = "fredoka", color = "#282728")) 
auc_wi
```

