---
title: "hooded_sprayer"
author: "Maxwel Coura Oliveira"
date: "3/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message = FALSE}
library(tidyverse)
library(lme4)
library(tidymodels)
library(lmerTest)
options(scipen = 999)
```

# Deposition --------------------------------------------------------------------------------

```{r missouri-data}
path_mo <- "./data/deposition/Deposition data_MO.xlsx"

missouri <- path_mo %>% 
  readxl::excel_sheets() %>% 
  set_names(c("downwind_mo", "upwind_mo", "inswath_mo")) %>% 
  map(readxl::read_excel, path = path_mo)



downwind_mo <- missouri$downwind_mo %>% 
  mutate(type = "downwind")
upwind_mo <- missouri$upwind_mo %>% 
  mutate('distance (m)' = NA,
         type = "upwind")
inswath_mo <- missouri$inswath_mo %>%
  mutate('distance (m)' = NA,
         type = "inswath") %>% 
  dplyr::select(-...8)

missouri <- downwind_mo %>% 
  bind_rows(upwind_mo) %>% 
  bind_rows(inswath_mo) %>% 
  mutate(location = "missouri")
```


```{r nebraska-data}
path_ne <- "./data/deposition/Deposition data_NE.xlsx"

nebraska <- path_ne %>% 
  readxl::excel_sheets() %>% 
  set_names(c("downwind_ne", "upwind_ne", "inswath_ne")) %>% 
  map(readxl::read_excel, path = path_ne)



downwind_ne <- nebraska$downwind_ne %>% 
  mutate(type = "downwind")
upwind_ne <- nebraska$upwind_ne %>% 
  mutate('distance (m)' = NA,
         type = "upwind")
inswath_ne <- nebraska$inswath_ne %>%
  mutate('distance (m)' = NA,
         type = "inswath")

nebraska <- downwind_ne %>% 
  bind_rows(upwind_ne) %>% 
  bind_rows(inswath_ne) %>% 
  mutate(location = "nebraska")
```


```{r wisconsin-data}
path_wi <- "./data/deposition/Deposition data_WI.xlsx"

wisconsin <- path_wi %>% 
  readxl::excel_sheets() %>% 
  set_names(c("downwind_wi", "upwind_wi", "inswath_wi")) %>% 
  map(readxl::read_excel, path = path_wi)



downwind_wi <- wisconsin$downwind_wi %>% 
  mutate(type = "downwind")
upwind_wi <- wisconsin$upwind_wi %>% 
  mutate('distance (m)' = NA,
         type = "upwind")
inswath_wi <- wisconsin$inswath_wi %>%
  mutate('distance (m)' = NA,
         type = "inswath")

wisconsin <- downwind_wi %>% 
  bind_rows(upwind_wi) %>% 
  bind_rows(inswath_wi) %>% 
  mutate(location = "wisconsin")
```


```{r}
data <- missouri %>% 
  bind_rows(nebraska) %>% 
  bind_rows(wisconsin) %>% 
  janitor::clean_names() %>% 
  rename(deposition = n_l_cm2) %>% 
  mutate_if(is_character, as_factor) %>% 
  mutate(distance_m = replace_na(distance_m, 0.000001)) %>% 
  mutate(distance_log = log10(distance_m),
         deposition_log = log10(deposition)) 
```





# Weather --------------------------------------------------------------------------------

```{r}
path_mo <- "./data/weather/Weather data_MO.xlsx"

missouri <- path_mo %>% 
  readxl::excel_sheets() %>% 
  set_names(c("downwind_mo", "upwind_mo", "inswath_mo")) %>% 
  map(readxl::read_excel, path = path_mo)

library(purrr)
file.list <- list.files(path="data/weather", pattern='*.xlsx')
file.list <- setNames(file.list, file.list) # only needed when you need an id-column with the file-names

df <- map_df(file.list, readxl::read_excel, .id = "id")
```

```{r message=FALSE}
data_path <- "./data/weather"   
files <- dir(data_path, pattern = '*.xlsx') 

weather_data <- files %>%
  map(~ readxl::read_excel(file.path(data_path, .)))
```


```{r message=FALSE, warning=FALSE}
weather_mo <- weather_data[[1]] %>% 
  janitor::row_to_names(row_number = 1)


weather_ne <- weather_data[[2]] %>% 
  janitor::row_to_names(row_number = 1)


weather_wi <- weather_data[[3]] %>% 
  janitor::row_to_names(row_number = 1)

weather <- weather_mo %>% 
  bind_rows(weather_ne) %>% 
  bind_rows(weather_wi) %>% 
  janitor::clean_names() %>% 
  mutate(date = lubridate::mdy_hms(date)) %>% 
  mutate_at(vars(pass:wind_speed_average_19), funs(as.double),
            vars(pass:wind_speed_average_19), funs(round(.,5))) %>% 
  rename_at(vars(wind_direction_max_9:wind_speed_average_13), paste0, "_voltage") %>% 
  rename_at(vars(wind_direction_min_14:wind_direction_average_16), paste0, "_degress") %>% 
  rename_at(vars(wind_speed_min_17:wind_speed_average_19), paste0, "_mph")
```


# Missouri

```{r}
data_mo <- data %>% 
  filter(type != "upwind") %>% 
  filter(location == "missouri") %>% 
  drop_na()

model_mo <- lmer(deposition_log ~ distance_log * sprayer * nozzle + 
         (1|block), REML = FALSE, data = data_mo)

summary(model_mo)
```

```{r}
data_mo %>% 
  ggplot(aes(x = distance_m, y = deposition, color = nozzle)) +
  geom_line(data = bind_cols(data_mo, pred = predict(model_mo)), aes(y = pred), size = 1)  +
  scale_x_log10() + 
  scale_y_log10()

```


```{r}
# Here you select the GDD you want. For instance, if you want to see the residual at the end season, you add GDD>1000
new_points <- expand.grid(distance_log = c(0, 1.477121, 1.778151), 
                          sprayer = c("Open", "Hood"),
                          nozzle = c("TTI", "AIXR", "ULD"))
new_points
```


```{r}
#Getting predited values
mo_pred <- augment(model_mo, new_data = new_points)
mo_pred %>% 
  ggplot(aes(x=distance_log, y = .fitted, color = nozzle)) +
  geom_smooth() +
  geom_point() +
  facet_grid(~ sprayer)
```


```{r}
#Getting conf intervals
library(merTools)
conf_int_mo <- predictInterval(model_mo, 
                         newdata = new_points)
conf_int_mo
```





```{r}
data1 <- data %>% 
  filter(type != "upwind") %>% 
  group_by(location) %>% 
  filter(location != "missouri") %>% 
  nest()
```




```{r}
linear_function <- function(df){
  lmer(deposition_log ~ distance_log * solution * sprayer * nozzle + 
         (1|block), REML = FALSE, data = df)
}
```


```{r}
data2 <- data1 %>% 
  mutate(model = map(data, linear_function),
         summary = map(model, summary))
```


```{r}
data2$model[[1]]
```


```{r}
plot(data3$model[[4]], type = "all", log = "")
```


```{r}
data3 %>% 
  unnest(summary)
```


```{r message=FALSE, warning=FALSE}
data3 %>% 
  unnest(summary)
```




