---
title: "inswath"
author: "Maxwel Coura Oliveira"
date: "3/29/2021"
output: html_document
---


## Deposition inswath ------------------------------------------------------

### Filter deposition dataset inswath

```{r}
inswath <-  data %>% 
  filter(type == "inswath")
```

### Test ANOVA assumptions

#### Normal distribution

```{r}
inswath %>% 
  ggplot(aes(x = deposition)) +
  geom_histogram()
# data has normal distribution
```

#### Homogeneity of variances

```{r}
bartlett.test(deposition ~ location, data = inswath)
# can't compare locations
```


### Data analysis

#### Filter location

```{r}
# nebraska and wisconsin 
inswath1 <- inswath %>% 
  group_by(location) %>% 
  nest() %>% 
  filter(location != "missouri")
```

#### Model

```{r}
model <- function(df){
  lmer(deposition ~ solution * sprayer * nozzle + (1|block), 
              REML = FALSE, data = df)
}
```

#### Fit models and ANOVA

```{r}
inswath2 <- inswath1 %>% 
  mutate(model = map(data, model),
         anova = map(model, anova))
```



### Nebraska

```{r}
model_ne <- inswath2$model[[1]]
# anova
anova(model_ne)
```

#### Solution x sprayer 

```{r}
lsmeans_ne1 <- emmeans(model_ne, ~ solution * sprayer, cont="pairwise", 
                      adjust="none", alpha=0.05)

lsmeans_ne1
```

##### Plot

```{r}
plot(lsmeans_ne1$emmeans, ~ solution * sprayer, comparisons=TRUE, 
     alpha=0.05, adjust="none") +
  labs(title = "Nebraska (Solution vs Sprayer)")
```


#### Solution x nozzle 

```{r}
lsmeans_ne2 <- emmeans(model_ne, ~ solution * nozzle, cont="pairwise", 
                      adjust="none", alpha=0.05)

lsmeans_ne2
```

##### Plot

```{r}
plot(lsmeans_ne2$emmeans, ~ solution * sprayer, comparisons=TRUE, 
     alpha=0.05, adjust="none") +
  labs(title = "Nebraska (Solution vs Nozzle)")
```



### Wisconsin

```{r}
model_wi <- inswath2$model[[2]]

#anova
anova(model_wi)
```


#### Solution x nozzle by sprayer

```{r}
lsmeans_wi <- emmeans(model_wi, ~ solution * nozzle * sprayer, cont="pairwise", 
                      adjust="none", alpha=0.05)
```
##### Plot 

```{r}
plot(lsmeans_wi$emmeans, ~ solution * nozzle * sprayer, comparisons=TRUE, 
     alpha=0.05, adjust="none") +
  labs(title = "Wisconsin (Solution x nozzle by sprayer")
```


```{r}
library(multcomp)
cld_wi <- cld(lsmeans_wi$emmeans, alpha=0.05, Letters=letters, adjust="none", reversed = TRUE)
cld_wi
```


```{r}
wi_insw <- as_tibble(cld_wi) %>% 
  unite("trt", c("solution", "sprayer", "nozzle"), sep = " ", remove = FALSE)
wi_insw 
```

```{r}
d <- wi_insw %>% 
  mutate(trt = factor(trt, levels = c(
    "Intact Hood TTI", "Intact Hood ULD", "Water Hood TTI",
    "Intact Hood AIXR", "Water Hood AIXR", "Water Hood ULD",
    "Intact Open TTI", "Water Open TTI", "Intact Open ULD",
    "Water Open ULD", "Water Open AIXR", "Intact Open AIXR"
  ))) %>% 
  ggplot(aes(x = fct_reorder(trt, emmean), y = emmean, color = trt, label = .group)) +
  geom_point(size = 2, stroke = 1) +
  geom_linerange(aes(ymin = lower.CL, ymax = upper.CL), size = 1.5) +
  scale_color_brewer(palette = "Paired") +
  coord_flip() +
  geom_text(nudge_y = 200) +
  geom_text(aes(x = 11.6, y = 550,
                label = "Slight difference in spray \nparticle deposition"),
            stat = "unique", family = "bell",
            size = 4, color = "darkcyan") +
  labs(title = "Deposition inswath",
       x = "", y = expression(paste("Spray particle deposition (\u03b7L/cm"^"2",")"))) +
  ylim(0, 1500) +
  theme_test() +
  theme(legend.position = "none",
        plot.title = element_markdown(family = "fredoka", color = "#282728")) 
d
```





### Missouri 

```{r}
data_missou <- inswath %>% 
  filter(location == "missouri")

#missou model has no solution levels
model_mo <- lmer(deposition ~ sprayer * nozzle + (1|block), 
              REML = FALSE, data = data_missou)

#anova
anova(model_mo)
```

#### Sprayer

```{r}
lsmeans_mo <- emmeans(model_mo, ~ sprayer, cont="pairwise", adjust="none", alpha=0.05)

lsmeans_mo
```

##### Plot

```{r}
plot(lsmeans_mo$emmeans, ~ herbicide, comparisons=TRUE, alpha=0.05, adjust="none") +
 labs(title = "Missouri (sprayer)")
```
