---
title: "weather"
author: "Maxwel Coura Oliveira"
date: "4/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Weather ----------------------------------------------------------------------

## Read weather dataset

```{r message=FALSE}
data_path <- "./data/weather"   
files <- dir(data_path, pattern = '*.xlsx') 

weather_data <- files %>%
  map(~ readxl::read_excel(file.path(data_path, .)))

weather_mo <- weather_data[[1]] %>% 
  janitor::row_to_names(row_number = 1)


weather_ne <- weather_data[[2]] %>% 
  janitor::row_to_names(row_number = 1)


weather_wi <- weather_data[[3]] %>% 
  janitor::row_to_names(row_number = 1)
```

## Tidy weather dataset

```{r message=FALSE}
weather <- weather_mo %>% 
  bind_rows(weather_ne) %>% 
  bind_rows(weather_wi) %>% 
  janitor::clean_names() %>% 
  mutate(date = lubridate::mdy_hms(date)) %>% 
  mutate_at(vars(pass:wind_speed_average_19), funs(as.double),
            vars(pass:wind_speed_average_19), funs(round(.,5))) %>% 
  rename_at(vars(wind_direction_max_9:wind_speed_average_13), paste0, "_voltage") %>% 
  rename_at(vars(wind_direction_min_14:wind_direction_average_16), paste0, "_degress") %>% 
  rename_at(vars(wind_speed_min_17:wind_speed_average_19), paste0, "_mph") %>% 
  filter(!is.na(pass))
```

