---
title: "hooded_sprayer"
author: "Maxwel Coura Oliveira"
date: "3/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message = FALSE}
library(tidyverse)
library(lme4)
library(tidymodels)
library(emmeans)
library(lmerTest)
library(broom)
options(scipen = 999)
```

# Deposition --------------------------------------------------------------------------------

```{r missouri-data}
path_mo <- "./data/deposition/Deposition data_MO.xlsx"

missouri <- path_mo %>% 
  readxl::excel_sheets() %>% 
  set_names(c("downwind_mo", "upwind_mo", "inswath_mo")) %>% 
  map(readxl::read_excel, path = path_mo)



downwind_mo <- missouri$downwind_mo %>% 
  mutate(type = "downwind")
upwind_mo <- missouri$upwind_mo %>% 
  mutate('distance (m)' = NA,
         type = "upwind")
inswath_mo <- missouri$inswath_mo %>%
  mutate('distance (m)' = NA,
         type = "inswath") %>% 
  dplyr::select(-...8)

missouri <- downwind_mo %>% 
  bind_rows(upwind_mo) %>% 
  bind_rows(inswath_mo) %>% 
  mutate(location = "missouri")
```


```{r nebraska-data}
path_ne <- "./data/deposition/Deposition data_NE.xlsx"

nebraska <- path_ne %>% 
  readxl::excel_sheets() %>% 
  set_names(c("downwind_ne", "upwind_ne", "inswath_ne")) %>% 
  map(readxl::read_excel, path = path_ne)



downwind_ne <- nebraska$downwind_ne %>% 
  mutate(type = "downwind")
upwind_ne <- nebraska$upwind_ne %>% 
  mutate('distance (m)' = NA,
         type = "upwind")
inswath_ne <- nebraska$inswath_ne %>%
  mutate('distance (m)' = NA,
         type = "inswath")

nebraska <- downwind_ne %>% 
  bind_rows(upwind_ne) %>% 
  bind_rows(inswath_ne) %>% 
  mutate(location = "nebraska")
```


```{r wisconsin-data}
path_wi <- "./data/deposition/Deposition data_WI.xlsx"

wisconsin <- path_wi %>% 
  readxl::excel_sheets() %>% 
  set_names(c("downwind_wi", "upwind_wi", "inswath_wi")) %>% 
  map(readxl::read_excel, path = path_wi)



downwind_wi <- wisconsin$downwind_wi %>% 
  mutate(type = "downwind")
upwind_wi <- wisconsin$upwind_wi %>% 
  mutate('distance (m)' = NA,
         type = "upwind")
inswath_wi <- wisconsin$inswath_wi %>%
  mutate('distance (m)' = NA,
         type = "inswath")

wisconsin <- downwind_wi %>% 
  bind_rows(upwind_wi) %>% 
  bind_rows(inswath_wi) %>% 
  mutate(location = "wisconsin")
```


```{r}
data <- missouri %>% 
  bind_rows(nebraska) %>% 
  bind_rows(wisconsin) %>% 
  janitor::clean_names() %>% 
  rename(deposition = n_l_cm2) %>% 
  mutate_if(is_character, as_factor) %>% 
  mutate(block = as_factor(block)) %>% 
  mutate(distance_m = replace_na(distance_m, 0)) %>% 
  mutate(distance_log = log10(distance_m),
         deposition_log = log10(deposition)) 
```

## Inswath

```{r}
inswath <-  data %>% 
  filter(type == "inswath")
```


```{r}
inswath %>% 
  ggplot(aes(x = deposition)) +
  geom_histogram()
```

```{r}
bartlett.test(deposition ~ location, data = inswath)
```


```{r}
inswath1 <- inswath %>% 
  group_by(location) %>% 
  nest() %>% 
  filter(location != "missouri")
```


```{r}
model <- function(df){
  lmer(deposition ~ solution * sprayer * nozzle + (1|block), 
              REML = FALSE, data = df)
}
```

```{r}
inswath2 <- inswath1 %>% 
  mutate(model = map(data, model),
         anova = map(model, anova))
```

```{r}
inswath2 %>% 
  unnest(anova)
```


### Nebraska

```{r}
model_ne <- inswath2$model[[1]]

anova(model_ne)
```


#### Solution x sprayer 

```{r}
lsmeans_ne1 <- emmeans(model_ne, ~ solution * sprayer, cont="pairwise", 
                      adjust="none", alpha=0.05)
```


##### Plot

```{r}
plot(lsmeans_ne1$emmeans, ~ solution * sprayer, comparisons=TRUE, 
     alpha=0.05, adjust="none") +
  labs(title = "Nebraska (Solution vs Sprayer")
```

#### Solution x nozzle 

```{r}
lsmeans_ne2 <- emmeans(model_ne, ~ solution * nozzle, cont="pairwise", 
                      adjust="none", alpha=0.05)

lsmeans_ne2
```

##### Plot

```{r}
plot(lsmeans_ne2$emmeans, ~ solution * sprayer, comparisons=TRUE, 
     alpha=0.05, adjust="none") +
  labs(title = "Nebraska (Solution vs Nozzle)")
```


### Wisconsin

```{r}
model_wi <- inswath2$model[[2]]

#anova
anova(model_wi)
```


#### Solution x nozzle by sprayer

```{r}
lsmeans_wi <- emmeans(model_wi, ~ solution * nozzle | sprayer, cont="pairwise", 
                      adjust="none", alpha=0.05)
```
##### Plot 

```{r}
plot(lsmeans_wi$emmeans, ~ solution * nozzle | sprayer, comparisons=TRUE, 
     alpha=0.05, adjust="none") +
  labs(title = "Wisconsin")
```



### Missouri 

```{r}
data_missou <- inswath %>% 
  filter(location == "missouri")

#missou model has no solution levels
model_mo <- lmer(deposition ~ sprayer * nozzle + (1|block), 
              REML = FALSE, data = data_missou)

#anova
anova(model_mo)
```

```{r}
lsmeans_mo <- emmeans(model_mo, ~ sprayer, cont="pairwise", adjust="none", alpha=0.05)

plot(lsmeans_mo$emmeans, ~ herbicide, comparisons=TRUE, alpha=0.05, adjust="none") +
 labs(title = "Missouri")
```

## Upwind

```{r}
upwind <- data %>% 
  filter(type == "upwind")
```


```{r}
upwind %>% 
  ggplot(aes(x = log(deposition))) +
  geom_histogram()
```

```{r}
bartlett.test(deposition ~ location, data = upwind)
```


### Nebraska

```{r}
ne_data <- upwind %>% 
  filter(location == "nebraska")
  
ne_model <- lmer(log(deposition) ~ solution * sprayer * nozzle + (1|block), 
              REML = FALSE, data = ne_data)
anova(ne_model)
```

```{r}
ne_lsmeans <- emmeans(ne_model, ~ solution, cont="pairwise", type = "response",
                      adjust="none", alpha=0.05)

plot(ne_lsmeans$emmeans, ~ solution, comparisons=TRUE, alpha=0.05, type = "response",
     adjust="none") +
 labs(title = "Nebraska - Upwind")
```

### Missouri

```{r}
mo_data <- upwind %>% 
  filter(location == "missouri")
  
mo_model <- lmer(log(deposition) ~ sprayer * nozzle + (1|block), 
              REML = FALSE, data = mo_data)

anova(mo_model)
```

### Wisconsin

```{r}
wi_data <- upwind %>% 
  filter(location == "wisconsin")
  
wi_model <- lmer(log(deposition) ~ solution * sprayer * nozzle + (1|block), 
              REML = FALSE, data = wi_data)

anova(wi_model)
```


## Downwind ------------------------------------------------------------------------

```{r}
data %>% 
  filter(type == "downwind") %>% 
  ggplot(aes(x = log(distance_m), y = log(deposition), color = nozzle)) +
  geom_point() +
  facet_grid(~ location)
```

```{r}
data %>% 
  filter(type == "downwind") %>% 
  ggplot(aes(x = log(deposition))) +
  geom_histogram() +
  facet_grid(~location)
```

### Downwind ------------------------------------------------------------------------


```{r}
data_dw <- data %>% 
  filter(type == "downwind")
```


```{r}
data_dw1 <- data_dw %>% 
  group_by(location, solution, sprayer, nozzle) %>% 
  nest()
```


```{r}
model <- function(df){
  lmer(log10(deposition) ~ log10(distance_m) + 
         (1|block), REML = FALSE, data = df)
}
```


```{r warning=FALSE, message = FALSE}
data_dw2 <- data_dw1 %>% 
  mutate(model = map(data, model),
         summary = map(model, tidy),
         confint = map(model, confint))
```


```{r}
data_dw2 %>% 
  unnest(summary) %>% 
  filter(effect == "fixed")
```

```{r}
params <- data_dw2 %>% 
  unnest(summary) %>% 
  filter(effect == "fixed") %>% 
  mutate(estimate_exp = exp(estimate)) %>% 
  dplyr::select(location, solution, sprayer, nozzle, term, estimate, std.error, statistic, p.value, estimate_exp) %>% 
  mutate(p.value = round(p.value, 3)) %>% 
  mutate(term = fct_recode(term,
                           "slope" = "log10(distance_m)"),
         term = fct_recode(term,
                           "Intercept" = "(Intercept)")) %>% 
  unite("trt", c("solution", "sprayer", "nozzle"), sep = " ", remove = FALSE)
```


```{r}
get_cis <- function(number){
  exp(data_dw2$confint[[number]]) %>% 
    as_tibble() %>% 
    slice_tail(n=2)
}

number <- as_tibble(c(1:30))

intervals <- number %>% 
  mutate(interval = map(value, get_cis)) %>% 
  unnest(interval)
```


```{r}
downwind_final <- params %>% 
  bind_cols(intervals) %>% 
  rename(lower = `2.5 %`,
         upper = `97.5 %`)
```


```{r}
downwind_final %>% 
  kableExtra::kable()
```


```{r}
downwind_final %>% 
  ggplot(aes(x = trt, y = estimate_exp, color = trt)) + 
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
  facet_grid(location ~ term, scales = "free") +
  coord_flip() +
  scale_color_brewer(palette = "Paired") +
  labs(y = "Estimates", x = "") +
  theme_bw() +
  theme(legend.position = "none") +
  ggsave("downwind.png", height = 7, width = 6)
```












# Weather --------------------------------------------------------------------------------


```{r message=FALSE}
data_path <- "./data/weather"   
files <- dir(data_path, pattern = '*.xlsx') 

weather_data <- files %>%
  map(~ readxl::read_excel(file.path(data_path, .)))
```


```{r message=FALSE, warning=FALSE}
weather_mo <- weather_data[[1]] %>% 
  janitor::row_to_names(row_number = 1)


weather_ne <- weather_data[[2]] %>% 
  janitor::row_to_names(row_number = 1)


weather_wi <- weather_data[[3]] %>% 
  janitor::row_to_names(row_number = 1)

weather <- weather_mo %>% 
  bind_rows(weather_ne) %>% 
  bind_rows(weather_wi) %>% 
  janitor::clean_names() %>% 
  mutate(date = lubridate::mdy_hms(date)) %>% 
  mutate_at(vars(pass:wind_speed_average_19), funs(as.double),
            vars(pass:wind_speed_average_19), funs(round(.,5))) %>% 
  rename_at(vars(wind_direction_max_9:wind_speed_average_13), paste0, "_voltage") %>% 
  rename_at(vars(wind_direction_min_14:wind_direction_average_16), paste0, "_degress") %>% 
  rename_at(vars(wind_speed_min_17:wind_speed_average_19), paste0, "_mph")
```

