---
title: "upwind"
author: "Maxwel Coura Oliveira"
date: "3/29/2021"
output: html_document
---

## Deposition upwind ------------------------------------------------------

### Filter deposition dataset upwind

```{r}
upwind <- data %>% 
  filter(type == "upwind")
```

### Test ANOVA assumptions

#### Normal distribution

```{r}
upwind %>% 
  ggplot(aes(x = deposition)) +
  geom_histogram() 
# not normalized
```

##### Log scale

```{r}
upwind %>% 
  ggplot(aes(x = log(deposition))) +
  geom_histogram()
# yes!
```

#### Homogeneity of variances

```{r}
bartlett.test(deposition ~ location, data = upwind)
# can't compare locations
```


### Nebraska

#### Filter upwind Nebraska

```{r}
ne_data <- upwind %>% 
  filter(location == "nebraska")
```

#### Model

```{r}
ne_model <- lmer(log(deposition) ~ solution * sprayer * nozzle + (1|block), 
              REML = FALSE, data = ne_data)
```

#### ANOVA 

```{r}
anova(ne_model)
```

#### Solution

```{r}
ne_lsmeans <- emmeans(ne_model, ~ solution, cont="pairwise", type = "response",
                      adjust="none", alpha=0.05)

ne_lsmeans
```

#### Plot

```{r}
plot(ne_lsmeans$emmeans, ~ solution, comparisons=TRUE, alpha=0.05, type = "response",
     adjust="none") +
 labs(title = "Nebraska (Solution)")
```

### Missouri

#### Filter upwind Missouri

```{r}
mo_data <- upwind %>% 
  filter(location == "missouri")
```

#### Model

```{r}
mo_model <- lmer(log(deposition) ~ sprayer * nozzle + (1|block), 
              REML = FALSE, data = mo_data)
```

#### ANOVA

```{r}
anova(mo_model)
```

### Wisconsin

#### Filter upwind Wisconsin

```{r}
wi_data <- upwind %>% 
  filter(location == "wisconsin")
```

#### Model

```{r}
wi_model <- lmer(log(deposition) ~ solution * sprayer * nozzle + (1|block), 
              REML = FALSE, data = wi_data)
```

#### ANOVA

```{r}
anova(wi_model)
```

```{r}
wi_lsmeans <- emmeans(wi_model, ~ solution*sprayer*nozzle, cont="pairwise", type = "response",
                      adjust="none", alpha=0.05)

wi_lsmeans
```

#### Plot

```{r warning=FALSE}
plot(wi_lsmeans$emmeans, ~ solution*sprayer*nozzle, comparisons=TRUE, alpha=0.05, type = "response",
     adjust="none") +
 labs(title = "Wisconsin (Solution)")
```


```{r}
library(multcomp)
cld_wiup <- cld(wi_lsmeans$emmeans, alpha=0.05, Letters=letters, adjust="none", reversed = TRUE)
cld_wiup
```


```{r}
wi_up <- as_tibble(cld_wiup) %>% 
  unite("trt", c("solution", "sprayer", "nozzle"), sep = " ", remove = FALSE)
wi_up 
```

```{r}
e <- wi_up %>% 
  mutate(trt = factor(trt, levels = c(
    "Intact Hood TTI", "Intact Hood ULD", "Water Hood TTI",
    "Intact Hood AIXR", "Water Hood AIXR", "Water Hood ULD",
    "Intact Open TTI", "Water Open TTI", "Intact Open ULD",
    "Water Open ULD", "Water Open AIXR", "Intact Open AIXR"
  ))) %>% 
  ggplot(aes(x = fct_reorder(trt, response), y = response,
             color = trt, label = .group)) +
  geom_point(size = 2, stroke = 1) +
  geom_linerange(aes(ymin = lower.CL, ymax = upper.CL), size = 1.5) +
  coord_flip() +
  geom_text(nudge_y = 1) +
  scale_color_brewer(palette = "Paired") +
  geom_text(aes(x = 1.5, y = 0.075,
                label = "No difference across \ntreatments"),
            stat = "unique", family = "bell",
            size = 4, color = "darkcyan") +
  labs(title = "Deposition upwind",
    x = "", y = expression(paste("Spray particle deposition (\u03b7/cm"^"2",")"))) +
  ylim(0, 0.1) +
  theme_test() +
   theme(legend.position = "none",
        plot.title = element_markdown(family = "fredoka", color = "#282728")) 
e
```